### ISSUE TITLE
Training New Reranker And Benchmarking

### ISSUE THREAD

**Issue by valayDave** [castorini/pygaggle#104]
Hello, 

Great work with a suite of libraries around pygaggle !. Really loved your work. It took me so little time to start work and experimenting on the doc-ranking task. 

I have created a new model to see experiments with the Reranker. I wanted to use MS Marco Dataset and see MRR.

I see that [this file]( https://github.com/castorini/pygaggle/blob/master/pygaggle/run/evaluate_document_ranker.py ) contains the main script to run for the Marco dataset.  

Can you provide a way to extend this module to bring in Outside models for testing and Benchmarking?

**Comment by ronakice** [comment]
Hey!

Thanks for the kind words.

https://github.com/castorini/pygaggle/blob/19b16d28b20bbcead359fc9b4086f33e5c7598f9/pygaggle/rerank/transformer.py#L117

You should look at creating a class like this for an external model if it isn't already included. 
And if your model works well you can possibly make a PR and add functionality for it in pygaggle too :) 

Then, create a new construction method:

https://github.com/castorini/pygaggle/blob/19b16d28b20bbcead359fc9b4086f33e5c7598f9/pygaggle/run/evaluate_document_ranker.py#L109

Once these two are done, you as is, you should be able to run the rest of the script with little to no changes.

If it is just a regular BERT/T5 with nothing on top, you can just change the function argument to `get_model`:

https://github.com/castorini/pygaggle/blob/19b16d28b20bbcead359fc9b4086f33e5c7598f9/pygaggle/rerank/transformer.py#L126

**Comment by lintool** [comment]
Closing... please reopen if there are any additional questions!
