### ISSUE TITLE
GPU by default?

### ISSUE THREAD

**Issue by MarcosFP97** [castorini/pygaggle#106]
Hi! First of all congrats for yout outstanding work!
I am using your pretrained models to rerank a custom collection, as exposed in your section **A Simple Reranking Example**. However, I would like to know if your T5 model fine tuned with MS MARCO uses any GPU available device by default to perform its predictions and reranking. If not I would appreciate any indication on how to achieve this.
Best,
Marcos

**Comment by rodrigonogueira4** [comment]
Hi @MarcosFP97, it should use the GPU by default if one is available: https://github.com/castorini/pygaggle/blob/19b16d28b20bbcead359fc9b4086f33e5c7598f9/pygaggle/rerank/transformer.py#L38

**Comment by MarcosFP97** [comment]
Thank you very much @rodrigonogueira4! That's great

**Comment by MarcosFP97** [comment]
Hi, I am sorry for bothering you again. When I launch my code the following warning appears:
```2020-11-06 10:50:42.400297: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64```

But the following command finds the GPU:
```print(torch.cuda.get_device_name(0))```
```Output: Tesla V100S-PCIE-32GB```

I don't know why the first warning is appearing and I would like to be sure that the GPU is being used. 
Best,
Marcos

**Comment by MarcosFP97** [comment]
Update:
I think this issue is related to my other one posted this morning #110. My intuition tells me that is a version-related problem between CUDA and Tensorflow. I am running this code in a Docker container with nvidia/cuda:10.1-base as base image and Tensorflow version 2.3.0.

I would appreciate any help, since I am relatively new to this Tensorflow, Cuda, and Deep Learning models world.
Best,
Marcos

**Comment by MXueguang** [comment]
@MarcosFP97 
I am not very sure, but you can use `watch nvidia-smi ` to see if the process is actually running on GPU.
I suspect it is an environment issue related to cuda&tensorflow version.
If you eventually find the process is not running on GPU, maybe you can share us the related commands in `Dockerfile` to help us further replicate&investigate the issue?

**Comment by MarcosFP97** [comment]
Hi @MXueguang, thank you very much for your response. As you suggested, the problem was related to cuda&tensorflow version. I managed to solve it by using Tensorflow official Docker image, which downloads `tensorflow==2.3.1` by default. This version was compatible with the CUDA 11 installed on my system.
