### ISSUE TITLE
update transformers dependency to latest transformers==4.0.0

### ISSUE THREAD

**Issue by MXueguang** [castorini/pygaggle#107]
current dependency transformers==2.10.0 is a bit outdated.

updating to transformers==3.4.0

conflicts are fixed already.
will create PR when monoT5 & monoBert's results are replicated on my end.

following warnings may need to be considered to update as well

- Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
- /u5/x93ma/anaconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py:1938: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(
- /u5/x93ma/anaconda3/lib/python3.8/site-packages/transformers/tokenization_t5.py:176: UserWarning: This sequence already has `</s>`. In future versions this behavior may lead to duplicated eos tokens being added.

**Comment by rodrigonogueira4** [comment]
Great! Looking forward to the PR!

**Comment by ronakice** [comment]
@MXueguang bump it up to 4 maybe? Transformers v4.0.0-rc-1 is out and has breaking changes (possibly breaking T5 results, but in a good way?)

**Comment by rodrigonogueira4** [comment]
Hey @ronakice, but it is still a release candidate, right? I mean, it might be unstable for a while...

**Comment by ronakice** [comment]
I don't think we should really worry about that much, I don't think that will cause too many issues with transformers since it is always kinda a work in progress. Will be easier moving from release candidate to final version anyway (I assume by the time we are done with it we'll be having v4)!

**Comment by rodrigonogueira4** [comment]
Ok, SGTM!

**Comment by MXueguang** [comment]
close, see https://github.com/castorini/pygaggle/pull/118
