### ISSUE TITLE
Add Jupyter or Colab notebooks

### ISSUE THREAD

**Issue by daemon** [castorini/pygaggle#11]
Title says it all.

**Comment by mrkarezina** [comment]
Hi Ralph, have you already started working on a Colab notebook? I was trying to get more familiar with the project so I might end up making a notebook in the process.

What would be helpful to include or test in the notebook?

**Comment by daemon** [comment]
Hey, sounds good. No, I haven't started -- a getting started guide for BM25 would probably be the best, since everyone can run BM25 with or without a GPU. Beyond that, T5 is probably the next most important due to its high quality.

**Comment by mrkarezina** [comment]
Sounds good, i'll get started on that.

**Comment by ronakice** [comment]
Resolved in #18
