### ISSUE TITLE
Error when running monoBert experiment

### ISSUE THREAD

**Issue by estella98** [castorini/pygaggle#112]
after running the command `srun --mem=64G --cpus-per-task=2 --time=24:0:0 --gres=gpu:v100l:2 --pty bash` to get GPU access and enter interactive mode, the following error occurs when trying to install pyggagle using the command `pip3 install -r requirements.txt` ( I have tried both pip and pip3, both failed. )

> Failed building wheel for pyjnius
>   Running setup.py clean for pyjnius
> Failed to build pyjnius
> Installing collected packages: pydantic, scipy, threadpoolctl, scikit-learn, pytz, python-dateutil, pandas, Cython, pyjnius, pyserini, spacy, pyasn1, rsa, pyasn1-modules, cachetools, google-auth, oauthlib, requests-oauthlib, google-auth-oauthlib, zipp, importlib-metadata, markdown, werkzeug, absl-py, grpcio, tensorboard-plugin-wit, tensorboard, tokenizers, tqdm, transformers
>   Found existing installation: pydantic 1.7.2
>     Uninstalling pydantic-1.7.2:
>       Successfully uninstalled pydantic-1.7.2
>   Rolling back uninstall of pydantic
> Could not install packages due to an EnvironmentError: [Errno 30] Read-only file system: '/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/site-packages/pydantic-1.5.dist-info'

I tried to install it individually using the command `pip3 install --user pyjnius` which successfully installed cython-0.29.21 pyjnius-1.3.0 for me

I then continued with another `pip3 install -r requirements.txt`, getting following error:

> Installing collected packages: pytz, python-dateutil, pandas, scipy, threadpoolctl, scikit-learn, pyserini, spacy, cachetools, pyasn1, pyasn1-modules, rsa, google-auth, oauthlib, requests-oauthlib, google-auth-oauthlib, werkzeug, tensorboard-plugin-wit, absl-py, grpcio, zipp, importlib-metadata, markdown, tensorboard, tokenizers, tqdm, transformers
> Could not install packages due to an EnvironmentError: [Errno 30] Read-only file system: '/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/site-packages/pytz-2020.4.dist-info'

which I fixed using this new command ` pip3 install --user -r requirements.txt`

the steps above resolved the problems in pygaggle installation, next, when actually running the monoBert experiment, I got:

> ImportError: cannot import name 'AutoModel',

 which I solved by  `pip3 install --user torch'. 

> No module named 'thinc', 'catalogue'

, which I solved by pip3 install them individually.

I ended up getting stuck at here:

> Traceback (most recent call last):
>   File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/scratch/o3liu/pygaggle/pygaggle/run/evaluate_passage_ranker.py", line 16, in <module>
>     from pygaggle.rerank.transformer import (
>   File "/scratch/o3liu/pygaggle/pygaggle/rerank/transformer.py", line 11, in <module>
>     from .similarity import SimilarityMatrixProvider
>   File "/scratch/o3liu/pygaggle/pygaggle/rerank/similarity.py", line 5, in <module>
>     from pygaggle.model.encode import SingleEncoderOutput
>   File "/scratch/o3liu/pygaggle/pygaggle/model/__init__.py", line 6, in <module>
>     from .encode import *
>   File "/scratch/o3liu/pygaggle/pygaggle/model/encode.py", line 8, in <module>
>     from .tokenize import BatchTokenizer
>   File "/scratch/o3liu/pygaggle/pygaggle/model/tokenize.py", line 5, in <module>
>     from spacy.lang.en import English
>   File "/home/o3liu/.local/lib/python3.6/site-packages/spacy/__init__.py", line 12, in <module>
>     from . import pipeline
>   File "/home/o3liu/.local/lib/python3.6/site-packages/spacy/pipeline/__init__.py", line 4, in <module>
>     from .pipes import Tagger, DependencyParser, EntityRecognizer, EntityLinker
>   File "pipes.pyx", line 1, in init spacy.pipeline.pipes
>   File "gold.pxd", line 18, in init spacy.syntax.nn_parser
>   File "syntax/transition_system.pxd", line 38, in init spacy.gold
>   File "search.pxd", line 37, in init spacy.syntax.transition_system
> ValueError: thinc.extra.search.Beam size changed, may indicate binary incompatibility. Expected 120 from C header, got 112 from PyObject
> 
> 
>

**Comment by qguo96** [comment]
hi, @estella98. Thank you for your information.
This is what you should get when you try to install pyjnius by `pip install -r requirement.txt`
![Screenshot (1291)](https://user-images.githubusercontent.com/30187452/98694724-cf22ac80-233f-11eb-9472-731f879e5bb0.png)

Did you follow the cc-guide(https://github.com/castorini/onboarding/blob/master/docs/cc-guide.md) and upgrade setuptools before everything?

I just tried to install pygaggle without upgrading setuptools and I got the same error message ...

**Comment by Ji-Xin** [comment]
> Could not install packages due to an EnvironmentError: [Errno 30] Read-only file system: '/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/site-packages/pydantic-1.5.dist-info'

This looks like you are trying to install a package NOT in your environment. Did you activate the virtualenv/conda environment before the installation? You can check by running `which python` to see whether your personal environment is activated.

**Comment by estella98** [comment]
```
module load python/3.6        
pip install --no-index --upgrade pip 
```
Ignoring pip: markers 'python_version < "3"' don't match your environment
`pip install --no-index --upgrade pip`
Ignoring pip: markers 'python_version < "3"' don't match your environment
Yes I did, however I do not think the pip upgrading is doing anything. I also tried to not use python3 but that will throw errors later.

**Comment by estella98** [comment]
> > Could not install packages due to an EnvironmentError: [Errno 30] Read-only file system: '/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/site-packages/pydantic-1.5.dist-info'
> 
> This looks like you are trying to install a package NOT in your environment. Did you activate the virtualenv/conda environment before the installation? You can check by running `which python` to see whether your personal environment is activated.

**Comment by qguo96** [comment]
You can ignore that warning, and that warning shouldn't stop you from installing the package.
Did you upgrade `setuptools` before installing pygaggle?

**Comment by estella98** [comment]
> You can ignore that warning, and that warning shouldn't stop you from installing the package.
> Did you upgrade `setuptools` before installing pygaggle?

yes I did, I have done all the commands and still see the errors above.

**Comment by rayyang29** [comment]
Here are the commands I ran for a successful replication:

After entering interactive mode in CC, I ran
`module load python/3.6`
`virtualenv --no-download ~/ENV`
`source ~/ENV/bin/activate`
`pip install --no-index --upgrade pip`
`pip install --no-index --upgrade setuptools`

Then I followed the MS Marco Entire Dev Set instructions:
`git clone --recursive https://github.com/castorini/pygaggle.git`
`module load java`

I commented out the TensorFlow dependency in requirements.txt and installed separately with:
`pip install tensorflow_gpu'
Then I installed the remaining dependencies:
`pip install -r requirement.txt`
`pip install torch`

Then I performed the Data Prep section of the instructions.
Finally, I allocated a non-interactive job on CC and completed the rest of the replication.

**Comment by lintool** [comment]
Follow up here, did we sort out these issues?

**Comment by estella98** [comment]
Hi Jimmy, sorry for the delay. those days I was working on finishing up my work in internship and doing covid testing as I am leaving Canada these days. I will have more time working on this once I land in China and I will prioritize this work in my quarantine.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by estella98** [comment]
resolved

**Comment by estella98** [comment]
I successfully installed the packages and finished the dataprep step. But I got one error again when trying to run the monoBert experiment..
![image](https://user-images.githubusercontent.com/36647501/100655154-e2121680-3318-11eb-8f73-843fdcb7203f.png)

**Comment by ronakice** [comment]
Closing this for now, reopen if others encounter the same.
