### ISSUE TITLE
Error on model name

### ISSUE THREAD

**Issue by MarcosFP97** [castorini/pygaggle#121]
Hi,
I am using `MonoT5` reranker to rerank my own collection. I am trying to use non-default models, like this:

```
model_name = 'castorini/monot5-3b-med-msmarco'
tokenizer_name = 't5-3b'
reranker =  MonoT5(model_name, tokenizer_name)
```
However I am getting the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/src/app/pygaggle/pygaggle/rerank/transformer.py", line 33, in __init__
    self.device = next(self.model.parameters(), None).device
AttributeError: 'str' object has no attribute 'parameters'
```

I think that this is a version related issue with some package, but I am not sure which one is causing the problem (I am using `transformers==2.10.0` and I have also tried recently updated `transformers==4.0.0`).

I would appreciate any help,
Marcos

**Comment by ronakice** [comment]
```
model = MonoT5.get_model('castorini/monot5-3b-med-msmarco')
tokenizer = MonoT5.get_tokenizer('t5-3b')
reranker =  MonoT5(model, tokenizer)
```
should work! We'll clean this up a little soon.

**Comment by ronakice** [comment]
Closing for now. Feel free to open if you still have issues.
