### ISSUE TITLE
incompatibility of Pyserini version

### ISSUE THREAD

**Issue by Narabzad** [castorini/pygaggle#125]
Hello,

As it is said in Pygaggle library, the requirement for Pygaggle is pyserini 0.9.4.0. However there is a line in pygaggle that is incompatible with pyserini 0.9.4.0 i.e.,. 

pygaggle/pygaggle/rerank/base.py :

`from pyserini.pyclass import JSimpleSearcherResult`

It should be

`from pyserini.search import JSimpleSearcherResult`

to be compatible with pyserini latest version. Is this correct ?

**Comment by lintool** [comment]
Yes, please send PR to fix? Thanks!

**Comment by ronakice** [comment]
Resolved by #161
