### ISSUE TITLE
pygaggle can't be installed in Colab?

### ISSUE THREAD

**Issue by zhuzz1997CN** [castorini/pygaggle#126]
When i pip install pygaggle in colab,it could not find a version that satisfies the requirement pygaggle.The python version of colab is 3.6+,however,pygaggle need python version 3.7+. Are there any good ways to install pygaggle in colab?

**Comment by ronakice** [comment]
Can you try cloning it and installing it from source instead?

**Comment by zhuzz1997CN** [comment]
> Can you try cloning it and installing it from source instead?

I tried this ，cloning it and use python _**setup.py install_** to install it ,however,when i import pygaggle,it can't import other packages.
`/usr/local/lib/python3.6/dist-packages/pygaggle/pygaggle/logger.py in <module>()
----> 1 import coloredlogs
      2 import logging
      3 
      4 
      5 __all__ = []

ModuleNotFoundError: No module named 'coloredlogs'`

**Comment by zhuzz1997CN** [comment]
> Can you try cloning it and installing it from source instead?

I tried this ，cloning it and use **python setup.py install** to install it ,however,when i import pygaggle,it can't import other packages.
`/usr/local/lib/python3.6/dist-packages/pygaggle/pygaggle/logger.py in ()
----> 1 import coloredlogs
2 import logging
3
4
5 all = []

ModuleNotFoundError: No module named 'coloredlogs'`

**Comment by ronakice** [comment]
https://colab.research.google.com/drive/1Sg09O8VX-SYB-Iaouyvanc6kz2JZ0Xij?usp=sharing

This is how we generally do it. Seems like installing from setup.py isn't vibing well with colab.

**Comment by zhuzz1997CN** [comment]
> https://colab.research.google.com/drive/1Sg09O8VX-SYB-Iaouyvanc6kz2JZ0Xij?usp=sharing
> 
> This is how we generally do it. Seems like installing from setup.py isn't vibing well with colab.

Thank you for your reply！
