### ISSUE TITLE
update-index.sh not working

### ISSUE THREAD

**Issue by cronopioelectronico** [castorini/pygaggle#153]
The file [update-index.sh](https://github.com/castorini/pygaggle/blob/master/scripts/update-index.sh) contains a reference to a dropbox url that doesn't exist:
`INDEX_URL=${2:-https://www.dropbox.com/s/s3bylw97cf0t2wq/lucene-index-cord19-paragraph-2020-05-12.tar.gz}`

That script is referenced in the installations instructions in the [README](https://github.com/castorini/pygaggle/blob/master/README.md) file. However it doesn't look a required step except when working with the CORD-19 dataset.
Maybe it could be changed by some test index (smaller than CORD-19 or MS MARCO).

**Comment by ronakice** [comment]
Hey @cronopioelectronico , thanks for pointing this out, we fixed it in the recent PR. CORD-19 was not our test index, just happened to be that pygaggle initially started out catering only to CovidQA, so I removed that part from the readme, we will add a smaller index soon to quickly demonstrate our framework!

**Comment by cronopioelectronico** [comment]
Great! Thanks for the info @ronakice
