### ISSUE TITLE
Fine-tunning

### ISSUE THREAD

**Issue by arinaruck** [castorini/pygaggle#165]
Hi, I was wondering whether the library supports only a zero-shot approach for the new data or fine-tuning on my dataset could be performed as well?

**Comment by ronakice** [comment]
I'd suggest looking at training [here](https://github.com/castorini/pygaggle/blob/master/docs/experiments-monot5-tpu.md) and modifying the input file to whatever dataset you want to train on. 

In case you don't have access to TPUs, mesh supports GPUs too although we currently don't have instructions for that, we will in a bit, it should be modifiable taking a look at the actual repository.

**Comment by ronakice** [comment]
Closing issue, reopen if required!
