### ISSUE TITLE
Fix rerank function

### ISSUE THREAD

**Issue by rodrigonogueira4** [castorini/pygaggle#173]
All of our implementation of `Reranker.rerank()` do not actually rerank, only rescore a list of text objects. Hence, we can either:

1) Rename it to `rescore`
2) Perform the actual reranking inside each rerank implementation.

I'm in favor of 2), but let me know what you think.

**Comment by lintool** [comment]
My vote is for (2) also.

**Comment by ronakice** [comment]
Yup (2) sounds like the better option!

**Comment by rodrigonogueira4** [comment]
Ok, I will send a PR soon.

**Comment by ronakice** [comment]
Resolved!
