### ISSUE TITLE
duot5-3b release

### ISSUE THREAD

**Issue by yixuan-qiao** [castorini/pygaggle#179]
Hi,
Thanks for your excellent work. Carefully look through all models in the Hugging Face castorini repository, maybe **duot5-3b** is missing? Or are there plans to release :-)

**Comment by ronakice** [comment]
Hey, sorry this took a bit, but added [castorini/duot5-3b-msmarco](https://huggingface.co/castorini/duot5-3b-msmarco/tree/main)!
