### ISSUE TITLE
Download MS MARCO dev subset

### ISSUE THREAD

**Issue by XY2323819551** [castorini/pygaggle#192]
Hi, everyone, I met some issues when I was trying to download msmarco_ans_small.zip, errors as follows:

--2021-05-20 21:46:58--  https://www.dropbox.com/s/5xa5vjbjle0c8jv/msmarco_ans_small.zip
Resolving www.dropbox.com (www.dropbox.com)... 31.13.85.34, 2001::6ca0:a694
Connecting to www.dropbox.com (www.dropbox.com)|31.13.85.34|:443... failed: Connection timed out.
Connecting to www.dropbox.com (www.dropbox.com)|2001::6ca0:a694|:443... failed: Network is unreachable.

Could you give me a link where I can obtain this dataset???
Thank you all !!

**Comment by ronakice** [comment]
Hey @XY2323819551, the dropbox link works fine for me, are you not even able to open that on a browser?

**Comment by MXueguang** [comment]
@XY2323819551 if you are in ShangHai, you might need a VPN to access dropbox

**Comment by XY2323819551** [comment]
Thanks for you reply，I used VPN yesterday but failed，I put the link in the browse directly and got the file，what is confusing me is that the fold is very small？？



---Original---
From: "Xueguang Ma ***@***.***&gt;
Date: Fri, May 21, 2021 06:57 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [castorini/pygaggle] Download MS MARCO dev subset (#192)




 
@XY2323819551 if you are in ShangHai, you might need a VPN to access dropbox

**Comment by XY2323819551** [comment]
Thanks for very much！I have got it already，but the size of fold is very small，is it right？




---Original---
From: ***@***.***&gt;
Date: Fri, May 21, 2021 06:10 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [castorini/pygaggle] Download MS MARCO dev subset (#192)




 
Hey @XY2323819551, the dropbox link works fine for me, are you not even able to open that on a browser?

**Comment by MXueguang** [comment]
> Thanks for very much！I have got it already，but the size of fold is very small，is it right？

Yes, ~2MB, cuz it only contains topics and judgement, so not big.

**Comment by XY2323819551** [comment]
> > Thanks for very much！I have got it already，but the size of fold is very small，is it right？
> 
> Yes, ~2MB, cuz it only contains topics and judgement, so not big.

Thank you again! You are so kind!
