### ISSUE TITLE
jnius.JavaException: JVM exception occurred

### ISSUE THREAD

**Issue by XY2323819551** [castorini/pygaggle#193]
Hi, everyone! I tried to solve the issue many times but failed，who can help me? I built the enviroment using pip，I have tried several versions of anserini.

(/data/zhangxy/condenv/gaggle) zhangxy@gpu:/data/zhangxy/pygaggle$ python
Python 3.6.13 |Anaconda, Inc.| (default, Feb 23 2021, 21:15:04)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pygaggle.rerank.base import Query, Text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/zhangxy/pygaggle/pygaggle/rerank/base.py", line 5, in <module>
    from pyserini.search import JSimpleSearcherResult
  File "/data/zhangxy/condenv/gaggle/lib/python3.6/site-packages/pyserini/search/__init__.py", line 17, in <module>
    from ._base import Document, JDocument, JQuery, get_topics, get_topics_with_reader
  File "/data/zhangxy/condenv/gaggle/lib/python3.6/site-packages/pyserini/search/_base.py", line 34, in <module>
    JTopicReader = autoclass('io.anserini.search.topicreader.TopicReader')
  File "/data/zhangxy/condenv/gaggle/lib/python3.6/site-packages/jnius/reflect.py", line 229, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 26, in jnius.find_javaclass
  File "jnius/jnius_jvm_dlopen.pxi", line 91, in jnius.create_jnienv
jnius.JavaException: JVM exception occurred: io/anserini/search/topicreader/TopicReader has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 java.lang.UnsupportedClassVersionError

**Comment by MXueguang** [comment]
Hi @XY2323819551, what is your java version?
we support jdk11 only

**Comment by XY2323819551** [comment]
> Hi @XY2323819551, what is your java version?
> we support jdk11 only

It is jdk8，thanks for your reminder，I reinstalled JDK11 ，Now it's OK.

**Comment by Lanskttee** [comment]
hi! I installed jdk11, but I still met the similar error.

Traceback (most recent call last):
  File "D:\pycharm\KB-BINDER-main\few_shot_kbqa.py", line 12, in <module>
    from pyserini.search import FaissSearcher, LuceneSearcher
  File "D:\pycharm\venv\lib\site-packages\pyserini\search\__init__.py", line 17, in <module>
    from ._base import JQuery, JQueryGenerator, JDisjunctionMaxQueryGenerator, get_topics,\
  File "D:\pycharm\venv\lib\site-packages\pyserini\search\_base.py", line 31, in <module>
    JQuery = autoclass('org.apache.lucene.search.Query')
  File "D:\pycharm\venv\lib\site-packages\jnius\reflect.py", line 209, in autoclass
    c = find_javaclass(clsname)
  File "jnius\jnius_export_func.pxi", line 22, in jnius.find_javaclass
  File "jnius\jnius_utils.pxi", line 79, in jnius.check_exception
jnius.JavaException: JVM exception occurred: org/apache/lucene/search/Query has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 java.lang.UnsupportedClassVersionError

**Comment by lintool** [comment]
How are you installing JDK?

This suggests that you still have a JVM version issue:

```
jnius.JavaException: JVM exception occurred: org/apache/lucene/search/Query has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 java.lang.UnsupportedClassVersionError
```

For example on macOS, for me, I get:

```bash
% java --version
openjdk 11.0.9.1 2020-11-04 LTS
OpenJDK Runtime Environment Zulu11.43+55-CA (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+55-CA (build 11.0.9.1+1-LTS, mixed mode)
```

**Comment by Lanskttee** [comment]
> 

yeah, but I installed the oracle jdk and it looks like this:

java 11.0.19 2023-04-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.19+9-LTS-224)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.19+9-LTS-224, mixed mode)

**Comment by lintool** [comment]
When you type `java --version` in a shell what does it say?

**Comment by Lanskttee** [comment]
> When you type `java --version` in a shell what does it say?

it is like:

java 11.0.19 2023-04-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.19+9-LTS-224)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.19+9-LTS-224, mixed mode)

**Comment by lintool** [comment]
Consult this guide for Java class version numbers: https://stackoverflow.com/questions/9170832/list-of-java-class-file-format-major-version-numbers

According to the error, for some reason you are still running Java 8.

**Comment by zhenduow** [comment]
`export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"` worked for me.

The path should be where the JDK 11 is installed.

Multiple JDKs can be installed on a system. `java -version` does not necessarily show the JDK being used to run this code.

**Comment by dhh-chyc** [comment]
Why do I get an error when using OpenJDK 11：
Error occurred during initialization of boot layer
java.lang.module.FindException: Module jdk.incubator.vector not found
