### ISSUE TITLE
Replication results

### ISSUE THREAD

**Issue by wongalvis14** [castorini/pygaggle#20]
Results on Hydra
CUDA 10.0
Python 3.7.7
Pytorch 1.5.0

Table 1 refers to the table in page 5 of "Rapidly Bootstrapping a Question Answering Dataset for COVID-19" https://arxiv.org/pdf/2004.11339.pdf

BM25: (matches Table 1)
precision@1	0.15
recall@3	0.2163978494623656
recall@50	0.619758064516129
recall@1000	0.6318548387096774
mrr	0.24284268136968856
mrr@10	0.22115655401945727

BERT: (matches Table 1)
precision@1	0.08064516129032258
recall@3	0.1172043010752688
recall@50	0.6460061443932411
recall@1000	1.0
mrr	0.15878306593763689
mrr@10	0.13760880696364566

T5 (fine-tuned on MS MARCO): (does not match Table 1, misses about 1%)
precision@1	0.27419354838709675
recall@3	0.43502304147465437
recall@50	0.9305683563748081
recall@1000	1.0
mrr	0.4224002621206025
mrr@10	0.4097638248847927

**Comment by lintool** [comment]
@rodrigonogueira4 can you check?

**Comment by rodrigonogueira4** [comment]
Hi @wongalvis14, @lintool the difference with T5 is probably due to this commit: https://github.com/castorini/pygaggle/commit/3469584c283f6da43887ef0cf8f0292d56160916#diff-5b0372e42fa60f56502010013b7f72deR33

P@1 is now worse but R@3 and MRR are better.

Just to make sure this is the only difference, @wongalvis14, could you please rerun T5 with line 33 in pygaggle/rerank/transformer.py changed to "length=2"

**Comment by wongalvis14** [comment]
@rodrigonogueira4 

Hi,

It is line 41 on latest master.

The results are matched after changing that line to "length=2"

precision@1	0.28225806451612906
recall@3	0.40410906298003074
recall@50	0.9230990783410139
recall@1000	1.0
mrr	0.41510119151581487
mrr@10	0.4014592933947773

**Comment by rodrigonogueira4** [comment]
Great, so let's keep length=1 as this has shown much better performance on the ranking tasks. Regarding the lower P@1, that 0.8 difference might not be statistically significant as the test dataset is small.

**Comment by ronakice** [comment]
@wongalvis14  @rodrigonogueira4 I assume we can close this issue?

**Comment by ronakice** [comment]
Wait we have switched to the new dataset so this is no longer valid, closing!
