### ISSUE TITLE
What dose “GAR” in "Dense Passage Retrieval (DPR) Baselines" refer to ?

### ISSUE THREAD

**Issue by XY2323819551** [castorini/pygaggle#223]
Hello，I want to know whether the “GAR” in "Dense Passage Retrieval (DPR) Baselines" is the same thing in the paper which named "Generation-Augmented Retrieval for Open-Domain Question Answering"?  If it is, How dose "GAR" work in your  repository?
Thanks in advance.😊

**Comment by MXueguang** [comment]
Hi @XY2323819551,
we explained in this paper https://arxiv.org/abs/2104.05740.
tl;dr, we take the answer span prediction rule in the GAR work.
but we didn't use any generation etc from GAR work

**Comment by ronakice** [comment]
Resolving, open if required
