### ISSUE TITLE
Access checkpoints

### ISSUE THREAD

**Issue by Elfsong** [castorini/pygaggle#244]
Hi @MXueguang, may I ask how to access these checkpoints? 

> Checkpoints:
> sentence selection: gs://pongo-bucket/xueguang/vert5-repl/ss-train
> label prediction: gs://pongo-bucket/xueguang/vert5-repl/lp-train
> sentence selection (with dev): gs://pongo-bucket/xueguang/vert5erini/train/monot5-3B-LP-balanced-dev
> label prediction (with dev): gs://pongo-bucket/xueguang/vert5erini/train/monot5-3B-SS-balanced-dev

Thank you!

**Comment by MXueguang** [comment]
Hi @Elfsong, could you retry? I just modify the permission

**Comment by Elfsong** [comment]
It works! Thank you so much for your rapid reply!

**Comment by Elfsong** [comment]
Btw, there is an outdated parameter that may need to update in "Convert T5 output to sentence selection result file (in jsonl format)":
> parser.add_argument("--thres", type=float, required=True)

**Comment by Elfsong** [comment]
In the "Run T5 inference for sentence selection" section:
Should the gin file "operative_config.gin" be specified as "gs://t5-data/pretrained_models/3B/operative_config.gin"?
