### ISSUE TITLE
Add mono models to huggingface model-zoo and incorporate into pipeline

### ISSUE THREAD

**Issue by ronakice** [castorini/pygaggle#26]
As pointed out in [hedwig](https://github.com/castorini/hedwig/issues/56), Huggingface's model-zoo provides a simple way of loading models without having for us to manually download models each time we use it. Besides, adding that would also allow us to track how many times our models are being used. Hence, this will be a great feature to incorporate into pygaggle.

Begin with monoBERT-large (should be simple) (Name choice - monobert-large-msmarco) and then figure out how to do the same with monoT5 (monot5-base-msmarco).

**Comment by ronakice** [comment]
This is done in #29

**Comment by lintool** [comment]
Don't think the counters are working? https://huggingface.co/castorini/monobert-large-msmarco

**Comment by MXueguang** [comment]
> Don't think the counters are working? https://huggingface.co/castorini/monobert-large-msmarco

weird, maybe because we haven't create README.md model card for the models on hugging face repo. I'll create one and ask them when making PR.

**Comment by ronakice** [comment]
@MXueguang  run by the content of the card once you are done creating it, I'll note if anything needs changing! Thanks

**Comment by ronakice** [comment]
Hey @lintool, can't seem to find any model updated after May 15th. So might just be taking time.

**Comment by lintool** [comment]
haha, okay! thanks for following up!
