### ISSUE TITLE
Broken link in experiments-msmarco-document.md

### ISSUE THREAD

**Issue by joelrorseth** [castorini/pygaggle#265]
Hi, I'm following the document retrieval steps in `docs/experiments-msmarco-document.md`.  It appears that the link for the pre-built MS MARCO index is dead. Would it be possible to get an updated link? Here is the command / link in question:

`wget https://www.dropbox.com/s/awukuo8c0tkl9sc/index-msmarco-doc-20200527-a1ecfa.tar.gz`

**Comment by lintool** [comment]
Hi @joelrorseth try this one, which is more up to date: https://github.com/castorini/pyserini/blob/master/pyserini/prebuilt_index_info.py#L1020

Please send a PR to fix?

Thanks!

**Comment by joelrorseth** [comment]
Excellent, that seems to work, thanks for the quick response. I'd be happy to open a PR, I'll do that as soon as I finish the remainder of these instructions!

**Comment by joelrorseth** [comment]
Closing now, since the fix has been merged. Thanks for your help!
