### ISSUE TITLE
Try fixing MS MARCO encoding issues *before* pointwise re-ranking

### ISSUE THREAD

**Issue by ronakice** [castorini/pygaggle#28]
See if fixing encoding issues before re-ranking with monoT5/monoBERT has any effect on MRR@10 / Recall scores

Related work in first-stage ranking: [1](https://github.com/castorini/anserini/issues/1212) and [2](https://github.com/castorini/anserini/issues/945#issuecomment-576417312).

Start with smaller subsets, report, and scale up to the entire dev set.

**Comment by ronakice** [comment]
Also a few examples of the text followed by the tokenized representation will be great! I found that the representations *do* change but I'm not sure if they always do.

**Comment by MXueguang** [comment]
Fixed text for both queries and passages by using `ftfy`'s `fix_text()`

monoBERT:
result without fix:
```
precision@1	0.2761904761904762
recall@3	0.42698412698412697
recall@50	0.8174603174603176
recall@1000	0.8476190476190476
mrr	0.41089693612003686
mrr@10	0.4026795162509449
```
result with fix:
![611590364517_ pic_hd](https://user-images.githubusercontent.com/34487581/82776405-6d4bb480-9e7d-11ea-8dc6-3593d6eabc8c.jpg)
motoT5:
result without fix:
```
precision@1	0.26666666666666666
recall@3	0.4603174603174603
recall@50	0.8063492063492063
recall@1000	0.8476190476190476
mrr	0.3973368360121561
mrr@10	0.39044217687074834
```
result with fix:
![601590346555_ pic_hd](https://user-images.githubusercontent.com/34487581/82776402-68870080-9e7d-11ea-8b10-f62e57f378b8.jpg)
Original Passage:
```
Gout-friendly meals. Too much bread or alcohol can be a problem if you have gout, a condition
 in which uric-acid crystals form in the joints, causing pain, swelling, and inflammation. Ad
d purine-rich foodsâsuch as seafood and red meatâto the list and it can seem hard to find som
ething you can eat. Still, gout shouldnât keep you from enjoying your food. Stick to low-puri
ne fare, like that in the following recipes, to have a tasty meal without triggering an attac
k or making a flare-up worse.
```

Passage with `fix_text`:
```
Gout-friendly meals. Too much bread or alcohol can be a problem if you have gout, a condition
 in which uric-acid crystals form in the joints, causing pain, swelling, and inflammation. Ad
d purine-rich foods—such as seafood and red meat—to the list and it can seem hard to find som
ething you can eat. Still, gout shouldn't keep you from enjoying your food. Stick to low-puri
ne fare, like that in the following recipes, to have a tasty meal without triggering an attac
k or making a flare-up worse.
```

Token with `fix_text`:
```
['▁', 'Query', ':', '▁what', '▁foods', '▁are', '▁good', '▁', 'if', '▁you', '▁have', '▁', 'g',
 'out', '?', '▁Document', ':', '▁G', 'out', '-', 'friendly', '▁meals', '.', '▁Too', '▁much', 
'▁bread', '▁or', '▁alcohol', '▁can', '▁be', '▁', 'a', '▁problem', '▁', 'if', '▁you', '▁have',
 '▁', 'g', 'out', ',', '▁', 'a', '▁condition', '▁in', '▁which', '▁', 'uri', 'c', '-', 'a', 'c
id', '▁crystal', 's', '▁form', '▁in', '▁the', '▁joints', ',', '▁', 'causing', '▁pain', ',', '
▁swelling', ',', '▁and', '▁inflammation', '.', '▁Add', '▁pur', 'ine', '-', 'rich', '▁foods', 
'—', 'such', '▁as', '▁seafood', '▁and', '▁red', '▁meat', '—', 'to', '▁the', '▁list', '▁and', 
'▁it', '▁can', '▁seem', '▁hard', '▁to', '▁find', '▁something', '▁you', '▁can', '▁', 'eat', '.
', '▁Still', ',', '▁', 'g', 'out', '▁shouldn', "'", 't', '▁keep', '▁you', '▁from', '▁enjoying
', '▁your', '▁food', '.', '▁Stick', '▁to', '▁low', '-', 'pur', 'ine', '▁far', 'e', ',', '▁lik
e', '▁that', '▁in', '▁the', '▁following', '▁recipes', ',', '▁to', '▁have', '▁', 'a', '▁tasty'
, '▁meal', '▁without', '▁', 'triggering', '▁an', '▁attack', '▁or', '▁making', '▁', 'a', '▁fla
re', '-', 'up', '▁worse', '.', '▁Relevan', 't', ':', '</s>']
```

**Comment by ronakice** [comment]
@richard3983 can you report your results on the subset here too?

**Comment by richard3983** [comment]
Results after fixing encoding issues with `fix_text()`:
monoBERT:
<img width="697" alt="Screen Shot 2020-05-23 at 5 20 11 PM" src="https://user-images.githubusercontent.com/25696555/82820915-150eb580-9e71-11ea-833a-b2a889ac23cf.png">

monoT5:
<img width="699" alt="Screen Shot 2020-05-23 at 4 08 39 PM" src="https://user-images.githubusercontent.com/25696555/82820927-1d66f080-9e71-11ea-9b34-b500f5151797.png">

original text vs fixed text
<img width="700" alt="Screen Shot 2020-05-23 at 4 38 00 PM" src="https://user-images.githubusercontent.com/25696555/82821162-92d2c100-9e71-11ea-9397-c40b277213ca.png">

**Comment by MXueguang** [comment]
Result for second half of msmarco:
![631590476629_ pic_hd](https://user-images.githubusercontent.com/34487581/82887398-85edc480-9f7a-11ea-8f6e-c52a71b92443.jpg)

**Comment by MXueguang** [comment]
Result for first half of msmarco:
![651590556726_ pic_hd](https://user-images.githubusercontent.com/34487581/82980678-a5d5c480-a01c-11ea-9513-544268d75041.jpg)

**Comment by ronakice** [comment]
Closing this for the time being as we saw no real improvements!
