### ISSUE TITLE
collections.tar.gz cannot be found via dropbox url

### ISSUE THREAD

**Issue by aandyw** [castorini/pygaggle#289]
I'm trying to download the `collections.tar.gz` file through dropbox but it seems to be deleted.
```
wget https://www.dropbox.com/s/m1n2wf80l1lb9j1/collection.tar.gz
```
encounters an ERROR 404.

**Comment by lintool** [comment]
Hi @Pie31415 can you show us the landing page this URL comes from? I can't tell whose dropbox account owns this file?

**Comment by Pie31415** [comment]
The url from the "Data Prep" of the readme https://github.com/castorini/pygaggle/blob/master/docs/experiments-monot5-gpu.md

**Comment by ahadda5** [comment]
@Pie31415 did you find it?

**Comment by ahadda5** [comment]
Can get from msmarco [directly ](https://microsoft.github.io/msmarco/Datasets.html)
