### ISSUE TITLE
ModuleNotFoundError: No module named 'faiss'

### ISSUE THREAD

**Issue by SinghShreyas** [castorini/pygaggle#293]
When I am trying to run this line `from pygaggle.rerank.base import Query, Text` following the instruction of the README file, I am getting ModuleNotFoundError: No module named 'faiss'.

I have followed the installation instruction from the README file.

Any help in this would be appreciated!

**Comment by lintool** [comment]
Dup of https://github.com/castorini/pyserini/discussions/1232
