### ISSUE TITLE
Java Runtime Environment Error

### ISSUE THREAD

**Issue by yikee** [castorini/pygaggle#303]
Hi! I am getting the following error when implementing monoT5. 

> 2022-11-11 00:25:42 [INFO] utils: NumExpr defaulting to 8 threads.
2022-11-11 00:25:43 [INFO] loader: Loading faiss with AVX2 support.
2022-11-11 00:25:43 [INFO] loader: Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2022-11-11 00:25:43 [INFO] loader: Loading faiss.
2022-11-11 00:25:43 [INFO] loader: Successfully loaded faiss.
[thread 36611 also had an error][thread 36867 also had an error]
A fatal error has been detected by the Java Runtime Environment:
SIGSEGV (0xb) at pc=0x000000015791f061, pid=10980, tid=37123
JRE version: Java(TM) SE Runtime Environment (19.0.1+10) (build 19.0.1+10-21)
Java VM: Java HotSpot(TM) 64-Bit Server VM (19.0.1+10-21, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-amd64)
Problematic frame:
C  [_swigfaiss.cpython-39-darwin.so+0x43e061]  void __kmp_suspend_64<false, true>(int, kmp_flag_64<false, true>*)+0x21
Core dump will be written. Default location: /cores/core.10980
An error report file with more information is saved as:
/Users/yike/Desktop/pygaggle/hs_err_pid10980.log
If you would like to submit a bug report, please visit:
https://bugreport.java.com/bugreport/crash.jsp
Abort trap: 6

Can I get any help on this? Thanks. (I am using Java 19.0.1

**Comment by lintool** [comment]
As we documented here: https://github.com/castorini/pyserini#installation - you'll need to downgrade to Java 11.

**Comment by yikee** [comment]
still getting the same error after downgrading to Java 11

**Comment by lintool** [comment]
> JRE version: Java(TM) SE Runtime Environment (19.0.1+10) (build 19.0.1+10-21)
Java VM: Java HotSpot(TM) 64-Bit Server VM (19.0.1+10-21, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-amd64)

What version does it say now after you downgrade?

**Comment by yikee** [comment]
`JRE version: Java(TM) SE Runtime Environment 18.9 (11.0.17+10) (build 11.0.17+10-LTS-269)
Java VM: Java HotSpot(TM) 64-Bit Server VM 18.9 (11.0.17+10-LTS-269, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)`

**Comment by lintool** [comment]
Can you try the instructions here? https://github.com/castorini/pyserini/blob/master/docs/installation.md

In particular, try this conda env:

```
$ conda install -c conda-forge openjdk=11
```

**Comment by yikee** [comment]
still the same
`JRE version: OpenJDK Runtime Environment Zulu11.43+55-CA (11.0.9.1+1) (build 11.0.9.1+1-LTS)
Java VM: OpenJDK 64-Bit Server VM Zulu11.43+55-CA (11.0.9.1+1-LTS, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
`

**Comment by lintool** [comment]
Hrm... really not sure what to say... we've had no issues before on our end. Are you sure your paths are set correctly? I.e., different versions of Java on your machine, and Python is talking to the wrong version?
