### ISSUE TITLE
Decommission numbert

### ISSUE THREAD

**Issue by lintool** [castorini/pygaggle#42]
Hey @ronakice we should probably decommission the numbert repo?
https://github.com/castorini/numbert

Add a note to the README saying it's defunct, pointing to pygaggle? I'll archive it and make it read only on GitHub?

**Comment by ronakice** [comment]
Yep! numBERT has some useful code with respect to inference/training which we'd need eventually incorporate into pygaggle / our future training framework. Also, TPU support etc.  Just pointing it out so we remember to go back to it eventually to re-use code segments

**Comment by ronakice** [comment]
Done you can archive it!

**Comment by lintool** [comment]
Done!
