### ISSUE TITLE
evaluate/msmarco/msmarco_eval.py should be moved to anserini-eval repo

### ISSUE THREAD

**Issue by lintool** [castorini/pygaggle#46]
https://github.com/castorini/anserini-eval

**Comment by lintool** [comment]
Merged: https://github.com/castorini/anserini-eval/pull/2

I think the way submodules work you have to manually update the commit in the checked out version in pygaggle?

**Comment by lintool** [comment]
In the same commit, kill the version in this repo?

**Comment by ronakice** [comment]
> Merged: [castorini/anserini-eval#2](https://github.com/castorini/anserini-eval/pull/2)
> 
> I think the way submodules work you have to manually update the commit in the checked out version in pygaggle?

Yeah, it seems like it. At least for pygaggle, we probably only "rarely" need to update it for the time being.




> In the same commit, kill the version in this repo?

On it!

**Comment by lintool** [comment]
Closed by #47
