### ISSUE TITLE
Pertained T5 Reranker

### ISSUE THREAD

**Issue by santhoshkolloju** [castorini/pygaggle#53]
Hi ,

Do u have the pretrained T5 ranker uploaded to hugging face repo. or any other file sharing site

Thanks

**Comment by rodrigonogueira4** [comment]
Yes, the model and instructions on how to load it are available here:
https://huggingface.co/castorini/monot5-base-msmarco

**Comment by santhoshkolloju** [comment]
Thanks for the reply. While training did u down sample the negetive passages?

**Comment by rodrigonogueira4** [comment]
Yes, each positive passage was paired with a negative passage during training. You can learn more about how we trained the model in section 3.2 of https://arxiv.org/pdf/2003.06713.pdf

**Comment by santhoshkolloju** [comment]
Thanks that helps

**Comment by santhoshkolloju** [comment]
Please do share the training scripts if they are open sourced
