### ISSUE TITLE
Pygaggle for reranking msmacro passages without ground-truth labels 

### ISSUE THREAD

**Issue by Fatima-200159617** [castorini/pygaggle#57]
Hi,
Could you please advice on how to rerank msmacro passages without evaluation with monbert, duobert, and T5 using pygaggle?
I followed the instructions on the link below, and it seems providing qrels is not optional. 
https://github.com/castorini/pygaggle/blob/master/docs/experiments-msmarco-passage.md#re-ranking-with-monobert

**Comment by rodrigonogueira4** [comment]
The example in this pull request might help you: https://github.com/castorini/pygaggle/pull/58

**Comment by Fatima-200159617** [comment]
> 
> 
> The example in this pull request might help you: #58

Great. Thanks a lot. This is exactly what I was looking for.

**Comment by ronakice** [comment]
Closing with the merge of #58
