### ISSUE TITLE
PyGaggle replication on Colab

### ISSUE THREAD

**Issue by lintool** [castorini/pygaggle#72]
Add instructions for replicating MS MARCO on Colab (for users without local GPU resources):
https://github.com/castorini/pygaggle/blob/master/docs/experiments-msmarco-passage.md

... as well as the replication guides.

**Comment by qguo96** [comment]
replication on Colab is successful. A PR for replication log is created.
I would create a new PR for replication guides.

**Comment by lintool** [comment]
ref #76

**Comment by qguo96** [comment]
Guide to replicate on Colab with ssh. https://github.com/castorini/onboarding/blob/master/docs/colab-instructions.md
