### ISSUE TITLE
Writing replication guide to train monoBERT from scratch

### ISSUE THREAD

**Issue by lintool** [castorini/pygaggle#73]
We probably want to write this against Compute Canada resources - all Waterloo students can have access to it.

Once we get this set up, we can create the parallelism for lots of simple experiments - like all the various BERTology experiments we talked about...

**Comment by ronakice** [comment]
Is this relevant to pygaggle though since I thought the plan was to only do inference here?

**Comment by lintool** [comment]
That's a good question - do we eventually want to fold training into pygaggle also?

For doc2query, separate repo makes sense, but for ranking, I think eventually merging them all into a single repo is a worthy goal?

**Comment by jeffzhengye** [comment]
@lintool So where can we find the train tutorials if this part will not be included in pygaggle?

**Comment by lintool** [comment]
@crystina-z we have a generic train monoBERT guide for Caprelous that isn't CC specific, right? cc @andrewyates

**Comment by crystina-z** [comment]
yup @jeffzhengye @lintool it's [here](https://github.com/capreolus-ir/capreolus/blob/feature/msmarco_psg/docs/reproduction/MS_MARCO.md), for non-CC users, just normally installing capreolus should work

**Comment by jeffzhengye** [comment]
I was hoping to have everything in one or two repos. It seems things get too much complicated. 
I would suggest to have end-to-end tutorials for experiments (from data prepocessing--> training --> evaluation). 

But still Castorini did a great job.
