### ISSUE TITLE
PARADE replication in Capreolus

### ISSUE THREAD

**Issue by lintool** [castorini/pygaggle#89]
URAs and others interested in PyGaggle should also take a look at [Capreolus](https://github.com/capreolus-ir/capreolus), which is another neural IR toolkit that our group contributes to: https://github.com/capreolus-ir/capreolus

See https://dl.acm.org/doi/10.1145/3336191.3371868

Capreolus is a much more full-featured toolkit and has a lot more models.

It was developed before PyGaggle. PyGaggle sprang into being because we needed something quick-and-dirty for our TREC-COVID experiments.

The relationship between PyGaggle and Capreolus is evolving, but for certain experiments that we want to run, it makes much more sense to start with Capreolus.

For one, Capreolus has PARADE, which I'm [a big fan of](https://twitter.com/lintool/status/1296825713836908551). We have some ideas on follow-up experiments, so replicating the results might be a start: https://github.com/capreolus-ir/capreolus/blob/master/docs/reproduction/PARADE.md

**Comment by ronakice** [comment]
This should go into URA repo or something? Closing.
