### ISSUE TITLE
Complete monoBERT and monoT5 replication on ComputeCanada

### ISSUE THREAD

**Issue by lintool** [castorini/pygaggle#97]
If URAs use ComputeCanada resources, how long would it take to replicate full results on MS MARCO passage?

I think it'd be nice to have a full leaderboard replication. Esp. with monoT5, since it's still reasonably competitive wrt SOTA.

**Comment by qguo96** [comment]
I just replicate passage experiment on ComputeCanada.
I used a V100 (32 GB).
For monoBERT: it took 51:35 mins to re-rank, excluding time to preprocess queries and passages.
For monoT5: it took 23:26 mins to re-rank, excluding time to preprocess queries and passages.

**Comment by lintool** [comment]
Awesome! Is this on the entire dev set or still just the sample?

**Comment by qguo96** [comment]
It's just the sample ...
Sorry, I didn't notice that you want to run on the dev set.
I would replicate one more time on the dev set.

**Comment by lintool** [comment]
Yup, let's do the entire thing!

**Comment by qguo96** [comment]
For the entire dev set:
For monoBERT: it took 56 hours 54 mins to re-rank, excluding time to preprocess queries and passages.
![Screenshot (1242)](https://user-images.githubusercontent.com/30187452/95602159-80bd7d80-0a22-11eb-89d7-195f979b2396.png)

For monoT5: it took 26 hours 16 mins to re-rank, excluding time to preprocess queries and passages.
![Screenshot (1245)](https://user-images.githubusercontent.com/30187452/95602323-c0846500-0a22-11eb-960f-3ec5165c452f.png)

**Comment by rodrigonogueira4** [comment]
Interesting, monoBERT gave better results than the original paper: 0.379 vs 0.372. Also, monoT5 is slightly below what we get with the TF implementation: 0.3798 vs 0.3810.

Could you please confirm the number of queries?
Also, just to confirm, we are using BERT-Large and T5-base, right?

**Comment by qguo96** [comment]
I used `queries.dev.small.tsv` in this repo(https://github.com/castorini/duobert), so 6,980 queries from the MS MARCO dev set.
Yes, we are using BERT-Large and T5-base.

**Comment by rodrigonogueira4** [comment]
Ok, thanks!

**Comment by qguo96** [comment]
Is this query file the entire dev set?
I asked ronak and xueguang, but I want to confirm it again here.

**Comment by rodrigonogueira4** [comment]
Yes, it is the entire dev set.

**Comment by lintool** [comment]
What do we make of these (minor) differences?

**Comment by rodrigonogueira4** [comment]
I would suggest evaluating with a BERT-base model because then we can check if this improvement is due to differences in the TF vs HF implementation or we were just lucky.

Same for monoT5-large, so we can check if HF implementation yields consistently lower results or that was just noise.

**Comment by qguo96** [comment]
I re-run the experiment with monoT5-large and I get the same result as above ...

**Comment by rodrigonogueira4** [comment]
Could you please double-check? MRR@10 should be higher and it should be at least 3x slower.

**Comment by qguo96** [comment]
Sorry, I didn't notice that I used monoT5-base ...

**Comment by ronakice** [comment]
@qguo96 , do you have an update to this?

**Comment by qguo96** [comment]
I tried once with T5-large. It took `83:39:16`, 3x slower than T5-base.
```
precision@1 0.24384
recall@3    0.44801
recall@50   0.80128
recall@1000 0.86289
mrr         0.37978
mrr@10      0.37109
```

**Comment by lintool** [comment]
Effectiveness seems lower than expected?

**Comment by ronakice** [comment]
Yes, we need to properly compare inconsistencies between mesh-t5 and hgf-t5 before we push the next pygaggle and sort out what we can.

**Comment by lintool** [comment]
@ronakice Can we close this issue now?
